[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Las variables de entorno se configurarán en el panel de Netlify
# No las incluimos aquí por seguridad
